angular.module("myApp")
    .config(function($stateProvider,$urlRouterProvider){
        $urlRouterProvider.otherwise("/group");
        $urlRouterProvider.when("/group","/group/introduce");
        $stateProvider
            .state({
                name:"autonomy",
                url:"/autonomy",
                templateUrl:"view/autonomy.html"
            })
            .state({
                name:"group",
                url:"/group",
                templateUrl:"view/group.html"
            })
            .state({
                name:"home",
                url:"/home",
                templateUrl:"view/home.html"
            })
            .state({
                name:"party",
                url:"/party",
                templateUrl:"view/party.html"
            })
            .state({
                name:"group.introduce",
                url:"/introduce",
                templateUrl:"view/introduce.html"
            })
            .state({
                name:"group.see",
                url:"/see",
                templateUrl:"view/see.html"
            })
            .state({
                name:"group.summary",
                url:"/summary",
                templateUrl:"view/summary.html"
            })
            .state({
                name:"group.sees",
                url:"/sees",
                templateUrl:"view/sees.html",
                constroller:function($scope){
                    $scope.go=function(){
                        console.log('663')
                    }
                }
            })
    });